name: Looker CI

on:
  pull_request:
    branches:
      - main

jobs:
  lookml-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run LookML check
        run: |
          echo "running the ci validation..."

          if ls general/flights/*.lkml > /dev/null 2>&1; then
            echo "LookML file found"
          else
            echo "no LookML file found"
          exit 1
          fi

          
